### ISSUE TITLE
Footprint for RP2040

### ISSUE THREAD

**Issue by MKdent** [YuzukiHD/Yuzuki2040#2]
Hi, I'm really looking forward to let JLPCP manufacture this board as soon as smt service for rp2040 is available.
But I'm concerned about the footprint of your rp2040 and the one LCSC is showing. See picture. I'm concerned about orientation of the rp2040 .....
May you have a closer look to it? Thanks.

![image](https://user-images.githubusercontent.com/13108176/139674408-abad498a-2b7b-48fc-9c75-62a259bbbd61.png)

**Comment by YuzukiTsuru** [comment]
This package and LCSC package are identical, just in a different drawing way.
